repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff check
        entry: uv run ruff
        args: ["check", "--force-exclude", "--fix"]
        language: system
        types: [python]
      - id: pyrefly
        name: pyrefly
        entry: uv run pyrefly check
        language: system
        types: [python]
        pass_filenames: false
